function fkMatrix = fkMatrix_to_function(a,b,c,d)
%fkMatrix_to_function
%    fkMatrix = fkMatrix_to_function(A,B,C,D)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    09-Sep-2025 12:57:13

t2 = cos(a);
t3 = cos(d);
t4 = sin(a);
t5 = sin(d);
t6 = cos(1.5708);
t7 = sin(1.5708);
t8 = c+1.3858;
t11 = b-1.3858;
t9 = cos(t8);
t10 = sin(t8);
t12 = cos(t11);
t13 = sin(t11);
t14 = t2.*t12;
t15 = t4.*t12;
t16 = t2.*t13;
t17 = t4.*t13;
t24 = t7.*t9.*t12;
t25 = t7.*t10.*t12;
t26 = t7.*t9.*t13;
t27 = t7.*t10.*t13;
t18 = t6.*t14;
t19 = t6.*t15;
t20 = t6.*t16;
t21 = t6.*t17;
t28 = -t27;
t43 = t25+t26;
t22 = -t18;
t23 = -t21;
t29 = t15+t20;
t30 = t16+t19;
t44 = t24+t28;
t31 = t14+t23;
t32 = t17+t22;
t33 = t10.*t29;
t34 = t10.*t30;
t35 = t9.*t29;
t36 = t9.*t30;
t37 = t10.*t31;
t38 = t10.*t32;
t39 = t9.*t31;
t40 = t9.*t32;
t42 = -t39;
t45 = t33+t40;
t46 = t36+t37;
t47 = t34+t42;
mt1 = [-t3.*t47-t5.*t46,-t5.*t45+t3.*(t35-t38),-t3.*t43-t5.*t44,0.0,-t3.*t46+t5.*t47,-t3.*t45-t5.*(t35-t38),-t3.*t44+t5.*t43,0.0,-t4.*t7,t2.*t7,t6,0.0,t14.*1.3023e+2-t21.*1.3023e+2-t34.*1.24e+2+t39.*1.24e+2-t3.*t47.*(6.67e+2./5.0)-t5.*t46.*(6.67e+2./5.0),t15.*1.3023e+2+t20.*1.3023e+2+t35.*1.24e+2-t38.*1.24e+2-t5.*t45.*(6.67e+2./5.0)+t3.*(t35-t38).*(6.67e+2./5.0)];
mt2 = [t43.*-1.24e+2-t7.*t13.*1.3023e+2-t3.*t43.*(6.67e+2./5.0)-t5.*t44.*(6.67e+2./5.0)+9.6326e+1,1.0];
fkMatrix = reshape([mt1,mt2],4,4);
end
